### ISSUE TITLE
Errors out if secret contains no values

### ISSUE THREAD

**Issue by EricLemieux** [EricLemieux/kubectl-spy#28]
This secret, contains no values

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: default
type: Opaque
```

When you run `kubectl spy test`, this error is thrown

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:31:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Expected the value to look more like this
```json
{
    "test": {}
}
```
